image: node:14.17.3


pipelines:
  branches:
    master:
      - step:
          name: Build
          script:
            - apt-get update
            - apt-get install -y zip
            - zip application.zip -r * .[^.]* -x *.git* -x bitbucket-pipelines.yml -x node_modules/\* -x README.md
          artifacts:
            - application.zip
      - step:
          name: Deploy to Production
          deployment: Production
          trigger: automatic
          script:
            - pipe: atlassian/aws-code-deploy:1.0.0
              variables:
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                APPLICATION_NAME: $APPLICATION_NAME
                S3_BUCKET: $S3_BUCKET
                COMMAND: 'upload'
                ZIP_FILE: 'application.zip'
                VERSION_LABEL: 'master-0.1.$BITBUCKET_BUILD_NUMBER'
            - pipe: atlassian/aws-code-deploy:1.0.0
              variables:
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                APPLICATION_NAME: $APPLICATION_NAME
                DEPLOYMENT_GROUP: $DEPLOYMENT_GROUP
                S3_BUCKET: $S3_BUCKET
                COMMAND: 'deploy'
                WAIT: 'true'
                VERSION_LABEL: 'master-0.1.$BITBUCKET_BUILD_NUMBER'
                IGNORE_APPLICATION_STOP_FAILURES: 'true'
                FILE_EXISTS_BEHAVIOR: 'OVERWRITE'
